name: open_mustang_cli
description: >
  This package should be installed as global binary. It helps in generating all the necessary source file
  templates for a screen.
version: 1.0.3
repository: https://github.com/getwrench/open_mustang_cli

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.2

executables:
  omcli: open_mustang_cli
